# Generated by Django 5.1.6 on 2025-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('payment_request', 'Payment Request'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
